[package]
name = "rust-cowsay"
version = "0.1.0"
edition = "2021"
authors = ["Matt Smith <matthew.smith491@gmail.com>"]

[dependencies]
clap = "4.5.47"
rand = "0.9.2"
rust-embed = "8.7.2"

[[bin]]
name = "cowsay"
path = "src/main.rs"

[[bin]]
name = "cowthink"
path = "src/main.rs"
